version: '3'
services:
  app:
    build: ./
    command: npm start
    ports:
      - 8080:8080
    working_dir: /code/app/
    volumes:
      - ./:/code/app/:delegated
      - notused:/code/app/node_modules
      - ./package.json:/code/package.json
      #- ./package-lock.json:/code/package-lock.json

volumes:
  notused: